### ISSUE TITLE
老哥，你是不是忘记给netease用户添加额外的audio和video组了，没声音啊

### ISSUE THREAD

**Issue by lg0v0** [bestwu/docker-netease-cloud-music#1]
系统ubuntu16.04，以下是我自行解决的方法

这是我写的Dockerfile
FROM bestwu/netease-cloud-music:latest
LABEL name=netease-cloud-music
MAINTAINER lg0v0<lg841418957@gmail.com>

ENV AUDIO_GID=29 \
    VIDEO_GID=44 

RUN groupmod -o -g $AUDIO_GID audio && \
    groupmod -o -g $VIDEO_GID video && \
    usermod -G audio,video netease && \
    rm -rf /entrypoint.sh

ADD run.sh /
RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]

还有你的启动脚本里chown那一句是多余的。执行chown的时候music目录还不存在呢
music目录是你后面mkdir加了-p参数创建的，而且是以netease用户创建的，都不用改权限

我的run.sh文件就只是把你的启动脚本去掉那一句多余的，其他都没变

**Comment by top-bettercode** [comment]
声音是通过共享 /pulse/native 方式处理的，可查看说明中的docker挂载项和环境变量参数

chown那一句是处理docker挂载有music目录时，目录是root权限的问题

**Comment by lg0v0** [comment]
我运行你的镜像的时候，是按照说明进行操作的，但是就是没有声音。我上面的操作是参考了你的qq的Dockerfile，改了之后就有声音了。
chown那句原来是这个作用啊，没想那么多。

**Comment by top-bettercode** [comment]
共享 pulse的方式可能在一些系统上不行。

**Comment by vpzv** [comment]
老哥，能不写下 Ubuntu18 下怎么配置呢？还是没声音。docker 和驱动不是很熟哪。打开没声音。
